export const mockProducts = [
  {
    id: 101,
    barcode: "P-000101",
    category: "Lighting",
    price: 49.99,
    inStock: true,
    image_url: "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?w=800&q=80&auto=format&fit=crop",
    name: "LED Spotlight",
    description: "High-efficiency LED spotlight for indoor use",
    translations: {
      ar: { name: "كشاف LED", description: "كشاف LED عالي الكفاءة للاستخدام الداخلي" },
      en: { name: "LED Spotlight", description: "High-efficiency LED spotlight for indoor use" },
      zh: { name: "LED 聚光灯", description: "高效室内 LED 聚光灯" },
    },
  },
  {
    id: 102,
    barcode: "P-000102",
    category: "Renewable Energy",
    price: 299.0,
    inStock: true,
    image_url: "https://images.unsplash.com/photo-1509395176047-4a66953fd231?w=800&q=80&auto=format&fit=crop",
    name: "Solar Panel 400W",
    description: "Premium monocrystalline solar panel with high output",
    translations: {
      ar: { name: "لوح شمسي 400 واط", description: "لوح شمسي أحادي عالي الكفاءة بقدرة إنتاج قوية" },
      en: { name: "Solar Panel 400W", description: "Premium monocrystalline solar panel with high output" },
      zh: { name: "400W 太阳能板", description: "高效单晶太阳能板，输出功率高" },
    },
  },
  {
    id: 103,
    barcode: "P-000103",
    category: "Smart Home",
    price: 129.99,
    inStock: false,
    image_url: "https://images.unsplash.com/photo-1582719478250-24779572d1f3?w=800&q=80&auto=format&fit=crop",
    name: "Smart Thermostat",
    description: "Wi‑Fi enabled thermostat with app control",
    translations: {
      ar: { name: "منظم حرارة ذكي", description: "منظم حرارة يدعم Wi‑Fi مع تحكم عبر التطبيق" },
      en: { name: "Smart Thermostat", description: "Wi‑Fi enabled thermostat with app control" },
      zh: { name: "智能恒温器", description: "支持 Wi‑Fi 的恒温器，应用程序控制" },
    },
  },
  {
    id: 104,
    barcode: "P-000104",
    category: "Industrial",
    price: 449.0,
    inStock: true,
    image_url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80&auto=format&fit=crop",
    name: "Industrial Drill",
    description: "Heavy‑duty industrial drill for workshops",
    translations: {
      ar: { name: "مثقاب صناعي", description: "مثقاب صناعي متين للاستخدام في الورش" },
      en: { name: "Industrial Drill", description: "Heavy‑duty industrial drill for workshops" },
      zh: { name: "工业电钻", description: "适用于车间的重型工业电钻" },
    },
  },
  {
    id: 105,
    barcode: "P-000105",
    category: "Safety Equipment",
    price: 19.99,
    inStock: true,
    image_url: "https://images.unsplash.com/photo-1516822003754-cca485356ecb?w=800&q=80&auto=format&fit=crop",
    name: "Safety Helmet",
    description: "Impact‑resistant safety helmet with adjustable strap",
    translations: {
      ar: { name: "خوذة أمان", description: "خوذة أمان مقاومة للصدمات بحزام قابل للتعديل" },
      en: { name: "Safety Helmet", description: "Impact‑resistant safety helmet with adjustable strap" },
      zh: { name: "安全头盔", description: "抗冲击安全头盔，带可调节带" },
    },
  },
];


